package practice.wardrobe.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import practice.wardrobe.model.FavPair;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FAV_PAIR".
*/
public class FavPairDao extends AbstractDao<FavPair, Long> {

    public static final String TABLENAME = "FAV_PAIR";

    /**
     * Properties of entity FavPair.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UpperId = new Property(1, Long.class, "upperId", false, "UPPER_ID");
        public final static Property LowerId = new Property(2, Long.class, "lowerId", false, "LOWER_ID");
    };

    private DaoSession daoSession;


    public FavPairDao(DaoConfig config) {
        super(config);
    }
    
    public FavPairDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FAV_PAIR\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"UPPER_ID\" INTEGER," + // 1: upperId
                "\"LOWER_ID\" INTEGER);"); // 2: lowerId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FAV_PAIR\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FavPair entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long upperId = entity.getUpperId();
        if (upperId != null) {
            stmt.bindLong(2, upperId);
        }
 
        Long lowerId = entity.getLowerId();
        if (lowerId != null) {
            stmt.bindLong(3, lowerId);
        }
    }

    @Override
    protected void attachEntity(FavPair entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FavPair readEntity(Cursor cursor, int offset) {
        FavPair entity = new FavPair( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // upperId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // lowerId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FavPair entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUpperId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setLowerId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(FavPair entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(FavPair entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getClothItemDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getClothItemDao().getAllColumns());
            builder.append(" FROM FAV_PAIR T");
            builder.append(" LEFT JOIN CLOTH_ITEM T0 ON T.\"UPPER_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN CLOTH_ITEM T1 ON T.\"LOWER_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected FavPair loadCurrentDeep(Cursor cursor, boolean lock) {
        FavPair entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        ClothItem upper = loadCurrentOther(daoSession.getClothItemDao(), cursor, offset);
        entity.setUpper(upper);
        offset += daoSession.getClothItemDao().getAllColumns().length;

        ClothItem lower = loadCurrentOther(daoSession.getClothItemDao(), cursor, offset);
        entity.setLower(lower);

        return entity;    
    }

    public FavPair loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<FavPair> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<FavPair> list = new ArrayList<FavPair>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<FavPair> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<FavPair> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
